[package]
authors = [ "Margined Protocol" ]
edition = "2021"
name    = "margined-testing"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = [ "cosmwasm-std/backtraces" ]

[dependencies]
cosmrs            = { workspace = true }
cosmwasm-std      = { workspace = true }
margined-protocol = { workspace = true }
mock-query        = { workspace = true }
osmosis-std       = { workspace = true }
osmosis-test-tube = { workspace = true }
schemars          = { workspace = true }
serde             = { workspace = true }
serde_json        = { workspace = true }
