on: [push]

name: Code Coverage

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.69.0
          target: wasm32-unknown-unknown
          profile: minimal
          override: true

      - name: Compile contracts
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --lib --target wasm32-unknown-unknown --locked --workspace --exclude margined-testing
        env:
          RUSTFLAGS: "-C link-arg=-s"
      - run: cargo install cargo-tarpaulin
      - run: cargo tarpaulin --out Xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV }}
